Chore/better organisation
Sefiraat/Netheopoiesis pull request #11
Opened 2022-06-13 15:13 UTC by Sefiraat

2022-06-13 15:14 UTC, Sefiraat commented
Don't merge just yet :)

2022-06-14 11:40 UTC, J3fftw1 requested changes
After this LGTM

2022-06-14 11:47 UTC, Sefiraat commented on src/main/java/dev/sefiraat/netheopoiesis/api/events/CruxSpreadEvent.java
> +        return crux;
That's not nit picky, its just plain wrong on my part, ha

2022-06-14 11:56 UTC, J3fftw1 commented
LGTM.

2022-06-14 11:57 UTC, J3fftw1 approved these changes

2022-06-15 11:33 UTC, merged