Feature/commands
Sefiraat/Netheopoiesis pull request #17
Opened 2022-06-18 19:04 UTC by Sefiraat

Adds ACF and a few basic commands to manage mobcaps including a permission node tree

2022-06-18 20:04 UTC, J3fftw1 requested changes

2022-06-18 20:04 UTC, J3fftw1 commented on src/main/java/dev/sefiraat/netheopoiesis/implementation/commands/NetheoCommands.java
> +            }
we are looping through the for in either cases why dont we have it outside the if?

2022-06-18 20:04 UTC, J3fftw1 commented on src/main/java/dev/sefiraat/netheopoiesis/implementation/commands/NetheoCommands.java
> +        cap.killAllMobs();
```suggestion
        final MobCap mobCap = MobManager.getInstance().getMobCap(MobCapType.valueOf(mobCapType));
        final String message = "Mob Cap Purged";

       mobCap.killAllMobs();
```

2022-06-18 20:04 UTC, J3fftw1 commented on src/main/resources/plugin.yml
> +    default: op
does plugin.yml properly update?

2022-06-18 20:04 UTC, J3fftw1 commented on src/main/java/dev/sefiraat/netheopoiesis/managers/DispatchManager.java
> +    }
Is this formatted properly it looks a little weird

2022-06-18 20:42 UTC, Sefiraat commented on src/main/resources/plugin.yml
> +    default: op
How do you mean?

2022-06-18 20:42 UTC, Sefiraat commented on src/main/java/dev/sefiraat/netheopoiesis/managers/DispatchManager.java
> +    }
Yeah, steams look weird, especially if in another method. I could expand the lamba if you like, but I think this is fine?

2022-06-18 20:43 UTC, Sefiraat commented on src/main/java/dev/sefiraat/netheopoiesis/implementation/commands/NetheoCommands.java
> +            }
Ha yeah much better xD

2022-06-18 20:46 UTC, Sefiraat commented on pom.xml
> +        </dependency>
<img width="585" alt="image" src="https://user-images.githubusercontent.com/20646323/174456558-c94ed3a9-2e1e-45f6-a45b-360025737183.png">

A bit like Paper lib I assume

2022-06-18 21:53 UTC, J3fftw1 commented on src/main/java/dev/sefiraat/netheopoiesis/managers/DispatchManager.java
> +    }
nah its fine

2022-06-18 21:54 UTC, J3fftw1 commented on src/main/resources/plugin.yml
> +    default: op
remember the convo we had on discord about updating yml

2022-06-18 21:57 UTC, Sefiraat commented on src/main/resources/plugin.yml
> +    default: op
Oh, that doesn’t apply here, plugin.yml doesn’t leave the jar

2022-06-19 07:02 UTC, J3fftw1 approved these changes
Lgtm

2022-06-19 07:05 UTC, merged